#!/bin/sh

 ssh -o StrictHostKeyChecking=no -tt -i node-app@15.206.57.14  <<EOF       
     cd backend
     npm install
     git pull
     pm2 restart all
     echo 'Process completed successfully.'
     exit      
    EOF
